#! /bin/sh

set -e

cd /root/FixMyStreet/fixmystreet

COBRAND_NAME="hild1" # no spaces

PM="package FixMyStreet::Cobrand::$COBRAND_NAME;
use base 'FixMyStreet::Cobrand::Default';
sub country { return 'NO'; }
sub set_lang_and_domain {
    my ( $self, $lang, $unicode, $dir ) = @_;
    my $set_lang = mySociety::Locale::negotiate_language( 'en-gb,English,en_GB|nb,Norwegian,nb_NO', 'nb' );
    mySociety::Locale::gettext_domain( 'FixMyStreet', $unicode, $dir );
    mySociety::Locale::change();
    return $set_lang;
}
sub site_title { my ($self) = @_; return '$COBRAND_NAME'; }
1;"

makedirs() {
	mkdir ./templates/web/$COBRAND_NAME
	mkdir ./templates/web/$COBRAND_NAME/faq
	mkdir ./templates/email/$COBRAND_NAME
	mkdir ./web/cobrands/$COBRAND_NAME
}

copyfiles() {
	cp ./templates/web/fixmystreet/faq/faq-en-gb.html ./templates/web/$COBRAND_NAME/faq/faq-nb.html
	cp -r ./web/cobrands/default/* ./web/cobrands/$COBRAND_NAME/
}

makepm() {
	echo "$PM" > /perllib/FixMyStreet/Cobrand/$COBRAND_NAME.pm
}

makedirs
copyfiles
makepm

echo "Please update config:
ALLOWED_COBRANDS:
  - $COBRAND_NAME
  - fiksgatami
  - fixmystreet"
