#! /bin/sh

set -e

cd /root/FixMyStreet/fixmystreet

COBRAND_NAME="hild1" # no spaces

PM="package FixMyStreet::Cobrand::$COBRAND_NAME;
use base 'FixMyStreet::Cobrand::Default';
sub country { return 'NO'; }
sub set_lang_and_domain {
    my ( $self, $lang, $unicode, $dir ) = @_;
    my $set_lang = mySociety::Locale::negotiate_language( 'en-gb,English,en_GB|nb,Norwegian,nb_NO', 'nb' );
    mySociety::Locale::gettext_domain( 'FixMyStreet', $unicode, $dir );
    mySociety::Locale::change();
    return $set_lang;
}
sub site_title { my ($self) = @_; return '$COBRAND_NAME'; }
1;"

makedirs() {
	mkdir -p ./templates/web/$COBRAND_NAME
	mkdir -p ./templates/web/$COBRAND_NAME/faq
	mkdir -p ./templates/email/$COBRAND_NAME
	mkdir -p ./web/cobrands/$COBRAND_NAME
}

copyfiles() {
	cp ./templates/web/fixmystreet/faq/faq-en-gb.html ./templates/web/$COBRAND_NAME/faq/faq-nb.html
	cp -r ./web/cobrands/default/* ./web/cobrands/$COBRAND_NAME/
}

makepm() {
	echo "$PM" > ./perllib/FixMyStreet/Cobrand/$COBRAND_NAME.pm
}

change_config() {
	# Add several cobrands ( for testing )
	# This first expressing will be a charlie foxtrot if any more YAML-arrays are added to the configfile
	sed -e "/^.*-.*$/d" \
	-e "s#^ALLOWED_COBRANDS:.*\$#ALLOWED_COBRANDS:\\n - fixmystreet: 'fms'\\n - fiksgatami: 'fgm'\\n - $COBRAND_NAME#" \
	./conf/general.yml > ./conf/general.yml.new
	mv ./conf/general.yml.new ./conf/general.yml
	# Add only one cobrand ( prod )
}

makedirs
copyfiles
makepm
change_config

echo end
